---

- name: Disable IPv6 if it's enabled
  hosts: test

  tasks:
    - name: Check if IPv6 is enabled
      shell : ip a | grep inet6 || true
      register: output

    - block :
      - name  : Disable IPv6
        shell : grub2-editenv - set "$(grub2-editenv - list | grep kernelopts) ipv6.disable=1"

      - name  : Reboot server
        reboot:
      when: "'inet6' in output.stdout"

    - name: Check if IPv6 is disabled 1/2
      shell: ip a | grep inet6 || true
      register: output2

    - name: Check if IPv6 is disabled 2/2
      debug:
        msg: IPv6 is disabled
      when: "'' in output2.stdout"