---

- name: Install Zabbix Agent
  hosts: test

  tasks:
    - name : copy Zabbix agent
      copy :
        src : /etc/ansible/playbooks/Zabbix/zabbix-agent2-6.0.0-1.el8.x86_64.rpm
        dest: /tmp/zabbix-agent2-6.0.0-1.el8.x86_64.rpm

    - name : install Zabbix agent
      shell: rpm -i /tmp/zabbix-agent2-6.0.0-1.el8.x86_64.rpm

    - name : copy config file
      template:
        src : /etc/ansible/playbooks/Zabbix/config_file.j2
        dest: /etc/zabbix/zabbix_agent2.conf

    - name : specify psk key
      shell: echo 0b06bc24dcc89c2c5617290cc35ed5cc2d1e0f65b9831b7e6cadff502bae86ac > /etc/zabbix/zabbix_agent2.key

    - name   : enable Zabbix service
      service: name=zabbix-agent2 state=started enabled=yes

    - name : remove installation file
      shell: rm /tmp/zabbix-agent2-6.0.0-1.el8.x86_64.rpm -f