---

- name : set hostname
  shell: hostnamectl set-hostname {{ hname }}

- name: set root password
  shell: echo "root:{{ rpassw }}" | chpasswd

- name : add MTS repo
  shell: cd /etc/yum.repos.d/ && wget http://99rhrp01.bckp.local/rhel8.repo

- name : update RHEL
  shell: dnf update -y

- name : configure repo for backups
  shell: |
   mkdir /{{ rfolder }}
   pvcreate /dev/sdb
   vgcreate vg_repo /dev/sdb
   lvcreate vg_repo -l +100%FREE -n lv_repo
   mkfs.xfs -b size=4096 -m reflink=1,crc=1 /dev/mapper/vg_repo-lv_repo
   mkdir /{{ rfolder }}
   echo '/dev/mapper/vg_repo-lv_repo /{{ rfolder }} xfs defaults 0 0' >> /etc/fstab
   useradd -d /home/liruser -m liruser
   usermod -a -G wheel liruser
   mount /{{ rfolder }}
   chown liruser.liruser /{{ rfolder }}
   chmod 700 /{{ rfolder }}
   echo "liruser:{{ lpassw }}" | chpasswd

- name : add transport restart command to crontab
  shell: echo '  *  *  *  *  * root systemctl is-active --quiet veeamtransport || systemctl start veeamtransport' >> /etc/crontab

- name : copy Zabbix agent
  copy :
    src : zabbix-agent2-6.0.0-1.el8.x86_64.rpm
    dest: /tmp/zabbix-agent2-6.0.0-1.el8.x86_64.rpm

- name : install Zabbix agent
  shell: rpm -i /tmp/zabbix-agent2-6.0.0-1.el8.x86_64.rpm

- name : copy config file
  template:
    src : config_file.j2
    dest: /etc/zabbix/zabbix_agent2.conf

- name : specify psk key
  shell: echo 0b06bc24dcc89c2c5617290cc35ed5cc2d1e0f65b9831b7e6cadff502bae86ac > /etc/zabbix/zabbix_agent2.key

- name   : start Zabbix service
  service: name=zabbix-agent2 state=started enabled=yes

- name : remove Zabbix package
  shell: rm /tmp/zabbix-agent2-6.0.0-1.el8.x86_64.rpm -f